//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrijavaRegistracija
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbArtikl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbArtikl()
        {
            this.dbStavkaNarudzbe = new HashSet<dbStavkaNarudzbe>();
        }
    
        public int id_artikla { get; set; }
        public int ponuda_id { get; set; }
        public string naziv { get; set; }
        public string cijena { get; set; }
    
        public virtual dbPonuda dbPonuda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbStavkaNarudzbe> dbStavkaNarudzbe { get; set; }
    }
}
