//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrijavaRegistracija
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbKorisnickiRacun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbKorisnickiRacun()
        {
            this.dbPoruka = new HashSet<dbPoruka>();
            this.dbPoruka1 = new HashSet<dbPoruka>();
        }
    
        public int id_korisnika { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public string email { get; set; }
        public string adresa { get; set; }
        public string broj_telefona { get; set; }
    
        public virtual dbObicniKorisnik dbObicniKorisnik { get; set; }
        public virtual dbUgostiteljskiObjekt dbUgostiteljskiObjekt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbPoruka> dbPoruka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbPoruka> dbPoruka1 { get; set; }
    }
}
