//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrijavaRegistracija
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbNarudžba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbNarudžba()
        {
            this.dbRecenzija1 = new HashSet<dbRecenzija>();
            this.dbStavkaNarudzbe = new HashSet<dbStavkaNarudzbe>();
        }
    
        public int id_narudzbe { get; set; }
        public int ugostiteljski_obrt_id { get; set; }
        public int korisnik_id { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
    
        public virtual dbObicniKorisnik dbObicniKorisnik { get; set; }
        public virtual dbUgostiteljskiObjekt dbUgostiteljskiObjekt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbRecenzija> dbRecenzija1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbStavkaNarudzbe> dbStavkaNarudzbe { get; set; }
    }
}
