//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrijavaRegistracija
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbPoruka
    {
        public int id_poruke { get; set; }
        public int posiljatelj_id { get; set; }
        public int primatelj_id { get; set; }
        public string naslov { get; set; }
        public string tekst { get; set; }
    
        public virtual dbKorisnickiRacun dbKorisnickiRacun { get; set; }
        public virtual dbKorisnickiRacun dbKorisnickiRacun1 { get; set; }
    }
}
