//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrijavaRegistracija
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbRecenzija
    {
        public int narudzba_id { get; set; }
        public string komentar { get; set; }
        public Nullable<int> ocjena { get; set; }
        public int id_recenzije { get; set; }
    
        public virtual dbNarudžba dbNarudžba1 { get; set; }
    }
}
