//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrijavaRegistracija
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eat32Entities : DbContext
    {
        public eat32Entities()
            : base("name=eat32Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbArtikl> dbArtikl { get; set; }
        public virtual DbSet<dbKorisnickiRacun> dbKorisnickiRacun { get; set; }
        public virtual DbSet<dbNarudžba> dbNarudžba { get; set; }
        public virtual DbSet<dbObicniKorisnik> dbObicniKorisnik { get; set; }
        public virtual DbSet<dbPonuda> dbPonuda { get; set; }
        public virtual DbSet<dbPoruka> dbPoruka { get; set; }
        public virtual DbSet<dbRezervacija> dbRezervacija { get; set; }
        public virtual DbSet<dbUgostiteljskiObjekt> dbUgostiteljskiObjekt { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<dbRecenzija> dbRecenzija { get; set; }
        public virtual DbSet<dbStavkaNarudzbe> dbStavkaNarudzbe { get; set; }
        public virtual DbSet<dbPretplata> dbPretplata { get; set; }
    }
}
