-- MySQL Script generated by MySQL Workbench
-- Sat Apr  7 18:10:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Korisnik` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Korisnik` (
  `id_korisnika` INT NOT NULL AUTO_INCREMENT,
  `korisnicko_ime` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NULL,
  `tip_korisnika` VARCHAR(45) NOT NULL,
  `broj_telefona` VARCHAR(45) NULL,
  PRIMARY KEY (`id_korisnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ugostiteljski_obrt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ugostiteljski_obrt` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ugostiteljski_obrt` (
  `id_ugostiteljskog_obrta` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `broj_telefona` VARCHAR(45) NULL,
  `lokacija_x` DOUBLE NULL,
  `lokacija_y` DOUBLE NULL,
  `radno_vrijeme_pocetak` DATETIME NULL,
  `radno_vrijeme_kraj` DATETIME NULL,
  `prosjecna_ocjena` DOUBLE NULL,
  PRIMARY KEY (`id_ugostiteljskog_obrta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rezervacija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rezervacija` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rezervacija` (
  `id_rezervacije` INT NOT NULL AUTO_INCREMENT,
  `Ugostiteljski_obrt_id_ugostiteljskog_obrta` INT NOT NULL,
  `Korisnik_id_korisnika` INT NOT NULL,
  `broj_stolova` INT NOT NULL,
  PRIMARY KEY (`id_rezervacije`, `Ugostiteljski_obrt_id_ugostiteljskog_obrta`, `Korisnik_id_korisnika`),
  INDEX `fk_Ugostiteljski_obrt_has_Korisnik_Korisnik1_idx` (`Korisnik_id_korisnika` ASC),
  INDEX `fk_Ugostiteljski_obrt_has_Korisnik_Ugostiteljski_obrt_idx` (`Ugostiteljski_obrt_id_ugostiteljskog_obrta` ASC),
  CONSTRAINT `fk_Ugostiteljski_obrt_has_Korisnik_Ugostiteljski_obrt`
    FOREIGN KEY (`Ugostiteljski_obrt_id_ugostiteljskog_obrta`)
    REFERENCES `mydb`.`Ugostiteljski_obrt` (`id_ugostiteljskog_obrta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ugostiteljski_obrt_has_Korisnik_Korisnik1`
    FOREIGN KEY (`Korisnik_id_korisnika`)
    REFERENCES `mydb`.`Korisnik` (`id_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artikl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Artikl` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Artikl` (
  `id_artikla` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `cijena` INT NOT NULL,
  `popust` INT NULL,
  PRIMARY KEY (`id_artikla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ponuda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ponuda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ponuda` (
  `id_ponude` INT NOT NULL AUTO_INCREMENT,
  `artikl_id` INT NOT NULL,
  `ugostiteljski_obrt_id` INT NOT NULL,
  PRIMARY KEY (`id_ponude`, `artikl_id`, `ugostiteljski_obrt_id`),
  INDEX `fk_Artikl_has_Ugostiteljski_obrt_Ugostiteljski_obrt1_idx` (`ugostiteljski_obrt_id` ASC),
  INDEX `fk_Artikl_has_Ugostiteljski_obrt_Artikl1_idx` (`artikl_id` ASC),
  CONSTRAINT `fk_Artikl_has_Ugostiteljski_obrt_Artikl1`
    FOREIGN KEY (`artikl_id`)
    REFERENCES `mydb`.`Artikl` (`id_artikla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artikl_has_Ugostiteljski_obrt_Ugostiteljski_obrt1`
    FOREIGN KEY (`ugostiteljski_obrt_id`)
    REFERENCES `mydb`.`Ugostiteljski_obrt` (`id_ugostiteljskog_obrta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recenzija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recenzija` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recenzija` (
  `id_recenzije` INT NOT NULL AUTO_INCREMENT,
  `ugostiteljski_obrt_id` INT NOT NULL,
  `korisnik_id` INT NOT NULL,
  `komentar` TEXT NULL,
  `ocjena` INT NOT NULL,
  PRIMARY KEY (`id_recenzije`, `ugostiteljski_obrt_id`, `korisnik_id`),
  INDEX `fk_Ugostiteljski_obrt_has_Korisnik_Korisnik2_idx` (`korisnik_id` ASC),
  INDEX `fk_Ugostiteljski_obrt_has_Korisnik_Ugostiteljski_obrt1_idx` (`ugostiteljski_obrt_id` ASC),
  CONSTRAINT `fk_Ugostiteljski_obrt_has_Korisnik_Ugostiteljski_obrt1`
    FOREIGN KEY (`ugostiteljski_obrt_id`)
    REFERENCES `mydb`.`Ugostiteljski_obrt` (`id_ugostiteljskog_obrta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ugostiteljski_obrt_has_Korisnik_Korisnik2`
    FOREIGN KEY (`korisnik_id`)
    REFERENCES `mydb`.`Korisnik` (`id_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Narudžba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Narudžba` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Narudžba` (
  `id_narudzbe` INT NOT NULL AUTO_INCREMENT,
  `ugostiteljski_obrt_id` INT NOT NULL,
  `korisnik_id` INT NOT NULL,
  `datum` DATETIME NULL,
  `ukupan_iznos` DOUBLE NOT NULL,
  PRIMARY KEY (`id_narudzbe`, `ugostiteljski_obrt_id`, `korisnik_id`),
  INDEX `fk_Ugostiteljski_obrt_has_Korisnik_Korisnik3_idx` (`korisnik_id` ASC),
  INDEX `fk_Ugostiteljski_obrt_has_Korisnik_Ugostiteljski_obrt2_idx` (`ugostiteljski_obrt_id` ASC),
  CONSTRAINT `fk_Ugostiteljski_obrt_has_Korisnik_Ugostiteljski_obrt2`
    FOREIGN KEY (`ugostiteljski_obrt_id`)
    REFERENCES `mydb`.`Ugostiteljski_obrt` (`id_ugostiteljskog_obrta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ugostiteljski_obrt_has_Korisnik_Korisnik3`
    FOREIGN KEY (`korisnik_id`)
    REFERENCES `mydb`.`Korisnik` (`id_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stavka_narudzbe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Stavka_narudzbe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Stavka_narudzbe` (
  `id_stavke` INT NOT NULL AUTO_INCREMENT,
  `artikl_id` INT NOT NULL,
  `narudžba_id` INT NOT NULL,
  `kolicina` INT NOT NULL,
  INDEX `fk_Stavka_narudzbe_Narudžba1_idx` (`narudžba_id` ASC),
  PRIMARY KEY (`id_stavke`, `artikl_id`),
  INDEX `fk_Stavka_narudzbe_Artikl1_idx` (`artikl_id` ASC),
  CONSTRAINT `fk_Stavka_narudzbe_Narudžba1`
    FOREIGN KEY (`narudžba_id`)
    REFERENCES `mydb`.`Narudžba` (`id_narudzbe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stavka_narudzbe_Artikl1`
    FOREIGN KEY (`artikl_id`)
    REFERENCES `mydb`.`Artikl` (`id_artikla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
